In [55]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [56]:
df = pd.read_csv('../input/hcode-bot-conversations/dataset.csv')

In [57]:
# random sample 
df.iloc[32056:32554].tail(15)

,source,num1,num2,num3,num4,num5,num6,num7,num8,num9,num10
32539,4,4735,23675,118375,591875,2959375,14796875,73984375,369921875,1849609375,9248046875
32540,0,4,1,9,1,7,6,4,6,4,1
32541,1,7155,7157,7165,7168,7176,7177,7180,7183,7191,7198
32542,2,35960,143840,863040,3452160,27617280,110469120,552345600,2209382400,2209382400,6628147200
32543,3,1269,1274,1279,1284,1289,1294,1299,1304,1309,1314
32544,4,43530,217650,1088250,5441250,27206250,136031250,680156250,3400781250,17003906250,85019531250
32545,0,6,8,9,4,5,7,8,1,7,3
32546,1,3906,3908,3909,3915,3918,3922,3929,3934,3940,3943
32547,2,19809,118854,356562,1426248,5704992,5704992,11409984,102689856,102689856,718828992
32548,3,2531,2536,2541,2546,2551,2556,2561,2566,2571,2576
32549,4,5390,26950,134750,673750,3368750,16843750,84218750,421093750,2105468750,10527343750
32550,0,9,7,9,3,4,2,5,8,3,1
32551,1,2045,2051,2055,2064,2069,2077,2082,2088,2090,2098
32552,2,44590,312130,2809170,16855020,16855020,151695180,303390360,606780720,2427122880,19416983040
32553,3,4964,4969,4974,4979,4984,4989,4994,4999,5004,5009

In [58]:
num_cols = df.columns[1:]
num_cols

Index(['num1', 'num2', 'num3', 'num4', 'num5', 'num6', 'num7', 'num8', 'num9',
       'num10'],
      dtype='object')

# <center>Exploratory Data Analysis<center>

In [59]:
# Are there any negative numbers?
(df[num_cols]<0).any()

num1     False
num2     False
num3     False
num4     False
num5     False
num6     False
num7     False
num8     False
num9     False
num10    False
dtype: bool

In [60]:
# Are there any missing numbers?
df[num_cols].isna().sum()

num1     0
num2     0
num3     0
num4     0
num5     0
num6     0
num7     0
num8     0
num9     0
num10    0
dtype: int64

### DataFrames for each bot

In [61]:
df_0 = df.loc[df['source']==0, :]
df_1 = df.loc[df['source']==1, :]
df_2 = df.loc[df['source']==2, :]
df_3 = df.loc[df['source']==3, :]
df_4 = df.loc[df['source']==4, :]

### Bot 0

In [62]:
# for source 0, none of the output numbers are greater than 10 , i.e., bot 0 outputs single digit nos only
((df_0[num_cols]>10).sum(axis=1)>0).any()

False

In [63]:
# None of the other bots ,i.e. bots 1,2,3 or 4 output single digit no. more than once
print(df_1.loc[(df_1['num1']!=0) & (df_1[num_cols]<10).sum(axis=1)>1, :].shape)
print(df_2.loc[(df_2['num1']!=0) & (df_2[num_cols]<10).sum(axis=1)>1, :].shape)
print(df_3.loc[(df_3['num1']!=0) & (df_3[num_cols]<10).sum(axis=1)>1, :].shape)
print(df_4.loc[(df_4['num1']!=0) & (df_4[num_cols]<10).sum(axis=1)>1, :].shape)

(0, 11)
(0, 11)
(0, 11)
(0, 11)

In [64]:
# check whether the bot always outputs a non-decreasing number

df_0['is_non_decreasing'] = (df_0['num2']>=df_0['num1']) & (df_0['num3']>=df_0['num2']) & (df_0['num4']>=df_0['num3']) & (df_0['num5']>=df_0['num4']) & (df_0['num6']>=df_0['num5']) & (df_0['num7']>=df_0['num6']) & (df_0['num8']>=df_0['num7']) & (df_0['num9']>=df_0['num8']) & (df_0['num10']>=df_0['num9'])

df_1['is_non_decreasing'] = (df_1['num2']>=df_1['num1']) & (df_1['num3']>=df_1['num2']) & (df_1['num4']>=df_1['num3']) & (df_1['num5']>=df_1['num4']) & (df_1['num6']>=df_1['num5']) & (df_1['num7']>=df_1['num6']) & (df_1['num8']>=df_1['num7']) & (df_1['num9']>=df_1['num8']) & (df_1['num10']>=df_1['num9'])

df_2['is_non_decreasing'] = (df_2['num2']>=df_2['num1']) & (df_2['num3']>=df_2['num2']) & (df_2['num4']>=df_2['num3']) & (df_2['num5']>=df_2['num4']) & (df_2['num6']>=df_2['num5']) & (df_2['num7']>=df_2['num6']) & (df_2['num8']>=df_2['num7']) & (df_2['num9']>=df_2['num8']) & (df_2['num10']>=df_2['num9'])

df_3['is_non_decreasing'] = (df_3['num2']>=df_3['num1']) & (df_3['num3']>=df_3['num2']) & (df_3['num4']>=df_3['num3']) & (df_3['num5']>=df_3['num4']) & (df_3['num6']>=df_3['num5']) & (df_3['num7']>=df_3['num6']) & (df_3['num8']>=df_3['num7']) & (df_3['num9']>=df_3['num8']) & (df_3['num10']>=df_3['num9'])

df_4['is_non_decreasing'] = (df_4['num2']>=df_4['num1']) & (df_4['num3']>=df_4['num2']) & (df_4['num4']>=df_4['num3']) & (df_4['num5']>=df_4['num4']) & (df_4['num6']>=df_4['num5']) & (df_4['num7']>=df_4['num6']) & (df_4['num8']>=df_4['num7']) & (df_4['num9']>=df_4['num8']) & (df_4['num10']>=df_4['num9'])


print('\nBot 0: ', df_0['is_non_decreasing'].all(),'\nBot 1: ', df_1['is_non_decreasing'].all(), '\nBot 2: ', df_2['is_non_decreasing'].all(), '\nBot 3: ', df_3['is_non_decreasing'].all(),'\nBot 4: ', df_4['is_non_decreasing'].all(),)

Bot 0:  False
Bot 1:  True
Bot 2:  True
Bot 3:  True
Bot 4:  True

### Bot 2 & 4

In [65]:
# Analyzing divisibility of all the o/p numbers by 1st number for all bots

df_0['is_div_by_num1'] = (df_0['num2']%df_0['num1']) + (df_0['num3']%df_0['num1']) + (df_0['num4']%df_0['num1']) + (df_0['num5']%df_0['num1']) + (df_0['num6']%df_0['num1']) + (df_0['num7']%df_0['num1']) + (df_0['num8']%df_0['num1']) + (df_0['num9']%df_0['num1']) + (df_0['num10']%df_0['num1']) 

df_1['is_div_by_num1'] = (df_1['num2']%df_1['num1']) + (df_1['num3']%df_1['num1']) + (df_1['num4']%df_1['num1']) + (df_1['num5']%df_1['num1']) + (df_1['num6']%df_1['num1']) + (df_1['num7']%df_1['num1']) + (df_1['num8']%df_1['num1']) + (df_1['num9']%df_1['num1']) + (df_1['num10']%df_1['num1']) 

df_2['is_div_by_num1'] = (df_2['num2']%df_2['num1']) + (df_2['num3']%df_2['num1']) + (df_2['num4']%df_2['num1']) + (df_2['num5']%df_2['num1']) + (df_2['num6']%df_2['num1']) + (df_2['num7']%df_2['num1']) + (df_2['num8']%df_2['num1']) + (df_2['num9']%df_2['num1']) + (df_2['num10']%df_2['num1'])

df_3['is_div_by_num1'] = (df_3['num2']%df_3['num1']) + (df_3['num3']%df_3['num1']) + (df_3['num4']%df_3['num1']) + (df_3['num5']%df_3['num1']) + (df_3['num6']%df_3['num1']) + (df_3['num7']%df_3['num1']) + (df_3['num8']%df_3['num1']) + (df_3['num9']%df_3['num1']) + (df_3['num10']%df_3['num1']) 

df_4['is_div_by_num1'] = (df_4['num2']%df_4['num1']) + (df_4['num3']%df_4['num1']) + (df_4['num4']%df_4['num1']) + (df_4['num5']%df_4['num1']) + (df_4['num6']%df_4['num1']) + (df_4['num7']%df_4['num1']) + (df_4['num8']%df_4['num1']) + (df_4['num9']%df_4['num1']) + (df_4['num10']%df_4['num1']) 

print('\nBot 0: ', df_0['is_div_by_num1'].sum(),'\nBot 1: ', df_1['is_div_by_num1'].sum(), '\nBot 2: ', df_2['is_div_by_num1'].sum(), '\nBot 3: ', df_3['is_div_by_num1'].sum(),'\nBot 4: ', df_4['is_div_by_num1'].sum(),)

Bot 0:  1747863
Bot 1:  22457775
Bot 2:  0.0
Bot 3:  22449320
Bot 4:  0.0

Clearly, bot 2 and 4 output numbers that are a multiple of the first number that they output. <br>

In [66]:
df_0['5_times_prev'] = (df_0['num1']==0) | ((df_0['num2']/df_0['num1']==5) & (df_0['num3']/df_0['num2']==5) & (df_0['num4']/df_0['num3']==5) & (df_0['num5']/df_0['num4']==5) & (df_0['num6']/df_0['num5']==5) & (df_0['num7']/df_0['num6']==5) & (df_0['num8']/df_0['num7']==5) & (df_0['num9']/df_0['num8']==5) & (df_0['num10']/df_0['num9']==5) )

df_1['5_times_prev'] = (df_1['num1']==0) | ((df_1['num2']/df_1['num1']==5) & (df_1['num3']/df_1['num2']==5) & (df_1['num4']/df_1['num3']==5) & (df_1['num5']/df_1['num4']==5) & (df_1['num6']/df_1['num5']==5) & (df_1['num7']/df_1['num6']==5) & (df_1['num8']/df_1['num7']==5) & (df_1['num9']/df_1['num8']==5) & (df_1['num10']/df_1['num9']==5) )

df_2['5_times_prev'] = (df_2['num1']==0) | ((df_2['num2']/df_2['num1']==5) & (df_2['num3']/df_2['num2']==5) & (df_2['num4']/df_2['num3']==5) & (df_2['num5']/df_2['num4']==5) & (df_2['num6']/df_2['num5']==5) & (df_2['num7']/df_2['num6']==5) & (df_2['num8']/df_2['num7']==5) & (df_2['num9']/df_2['num8']==5) & (df_2['num10']/df_2['num9']==5) )

df_3['5_times_prev'] = (df_3['num1']==0) | ((df_3['num2']/df_3['num1']==5) & (df_3['num3']/df_3['num2']==5) & (df_3['num4']/df_3['num3']==5) & (df_3['num5']/df_3['num4']==5) & (df_3['num6']/df_3['num5']==5) & (df_3['num7']/df_3['num6']==5) & (df_3['num8']/df_3['num7']==5) & (df_3['num9']/df_3['num8']==5) & (df_3['num10']/df_3['num9']==5) )

df_4['5_times_prev'] = (df_4['num1']==0) | ((df_4['num2']/df_4['num1']==5) & (df_4['num3']/df_4['num2']==5) & (df_4['num4']/df_4['num3']==5) & (df_4['num5']/df_4['num4']==5) & (df_4['num6']/df_4['num5']==5) & (df_4['num7']/df_4['num6']==5) & (df_4['num8']/df_4['num7']==5) & (df_4['num9']/df_4['num8']==5) & (df_4['num10']/df_4['num9']==5) )

print('\nBot 0: ', df_0['5_times_prev'].all(),'\nBot 1: ', df_1['5_times_prev'].all(), '\nBot 2: ', df_2['5_times_prev'].all(), '\nBot 3: ', df_3['5_times_prev'].all(),'\nBot 4: ', df_4['5_times_prev'].all(),)

Bot 0:  False
Bot 1:  False
Bot 2:  False
Bot 3:  False
Bot 4:  True

**** Bot 4 always outputs a number equal to 5 times the previous number, i.e., <b><i>num2 = 5 x num1, num3 = 5 x num2</i></b> ....and so on

### Bot 3

In [67]:
# Analyzing difference of o/p numbers by previous o/p number for all bots
df_0['is_diff_less_than_10'] = ((df_0['num2']-df_0['num1'])<10) & ((df_0['num3']-df_0['num2'])<10) & ((df_0['num4']-df_0['num3'])<10) & ((df_0['num5']-df_0['num4'])<10) & ((df_0['num6']-df_0['num5'])<10) & ((df_0['num7']-df_0['num6'])<10) & ((df_0['num8']-df_0['num7'])<10) & ((df_0['num9']-df_0['num8'])<10) & ((df_0['num10']-df_0['num9'])<10)

df_1['is_diff_less_than_10'] = ((df_1['num2']-df_1['num1'])<10) & ((df_1['num3']-df_1['num2'])<10) & ((df_1['num4']-df_1['num3'])<10) & ((df_1['num5']-df_1['num4'])<10) & ((df_1['num6']-df_1['num5'])<10) & ((df_1['num7']-df_1['num6'])<10) & ((df_1['num8']-df_1['num7'])<10) & ((df_1['num9']-df_1['num8'])<10) & ((df_1['num10']-df_1['num9'])<10)

df_2['is_diff_less_than_10'] = ((df_2['num2']-df_2['num1'])<10) & ((df_2['num3']-df_2['num2'])<10) & ((df_2['num4']-df_2['num3'])<10) & ((df_2['num5']-df_2['num4'])<10) & ((df_2['num6']-df_2['num5'])<10) & ((df_2['num7']-df_2['num6'])<10) & ((df_2['num8']-df_2['num7'])<10) & ((df_2['num9']-df_2['num8'])<10) & ((df_2['num10']-df_2['num9'])<10)

df_3['is_diff_less_than_10'] = ((df_3['num2']-df_3['num1'])<10) & ((df_3['num3']-df_3['num2'])<10) & ((df_3['num4']-df_3['num3'])<10) & ((df_3['num5']-df_3['num4'])<10) & ((df_3['num6']-df_3['num5'])<10) & ((df_3['num7']-df_3['num6'])<10) & ((df_3['num8']-df_3['num7'])<10) & ((df_3['num9']-df_3['num8'])<10) & ((df_3['num10']-df_3['num9'])<10)

df_4['is_diff_less_than_10'] = ((df_4['num2']-df_4['num1'])<10) & ((df_4['num3']-df_4['num2'])<10) & ((df_4['num4']-df_4['num3'])<10) & ((df_4['num5']-df_4['num4'])<10) & ((df_4['num6']-df_4['num5'])<10) & ((df_4['num7']-df_4['num6'])<10) & ((df_4['num8']-df_4['num7'])<10) & ((df_4['num9']-df_4['num8'])<10) & ((df_4['num10']-df_4['num9'])<10)


print('\nBot 0: ', df_0['is_diff_less_than_10'].all(),'\nBot 1: ', df_1['is_diff_less_than_10'].all(), '\nBot 2: ', df_2['is_diff_less_than_10'].all(), '\nBot 3: ', df_3['is_diff_less_than_10'].all(),'\nBot 4: ', df_4['is_diff_less_than_10'].all(),)

Bot 0:  True
Bot 1:  True
Bot 2:  False
Bot 3:  True
Bot 4:  False

In [68]:
df_2['is_diff_less_than_10'].value_counts()

False    99989
True        11
Name: is_diff_less_than_10, dtype: int64

In [69]:
# Analyzing difference of o/p numbers by previous o/p number for all bots
df_0['is_diff_5'] = ((df_0['num2']-df_0['num1'])==5) & ((df_0['num3']-df_0['num2'])==5) & ((df_0['num4']-df_0['num3'])==5) & ((df_0['num5']-df_0['num4'])==5) & ((df_0['num6']-df_0['num5'])==5) & ((df_0['num7']-df_0['num6'])==5) & ((df_0['num8']-df_0['num7'])==5) & ((df_0['num9']-df_0['num8'])==5) & ((df_0['num10']-df_0['num9'])==5)

df_1['is_diff_5'] = ((df_1['num2']-df_1['num1'])==5) & ((df_1['num3']-df_1['num2'])==5) & ((df_1['num4']-df_1['num3'])==5) & ((df_1['num5']-df_1['num4'])==5) & ((df_1['num6']-df_1['num5'])==5) & ((df_1['num7']-df_1['num6'])==5) & ((df_1['num8']-df_1['num7'])==5) & ((df_1['num9']-df_1['num8'])==5) & ((df_1['num10']-df_1['num9'])==5)

df_2['is_diff_5'] = ((df_2['num2']-df_2['num1'])==5) & ((df_2['num3']-df_2['num2'])==5) & ((df_2['num4']-df_2['num3'])==5) & ((df_2['num5']-df_2['num4'])==5) & ((df_2['num6']-df_2['num5'])==5) & ((df_2['num7']-df_2['num6'])==5) & ((df_2['num8']-df_2['num7'])==5) & ((df_2['num9']-df_2['num8'])==5) & ((df_2['num10']-df_2['num9'])==5)

df_3['is_diff_5'] = ((df_3['num2']-df_3['num1'])==5) & ((df_3['num3']-df_3['num2'])==5) & ((df_3['num4']-df_3['num3'])==5) & ((df_3['num5']-df_3['num4'])==5) & ((df_3['num6']-df_3['num5'])==5) & ((df_3['num7']-df_3['num6'])==5) & ((df_3['num8']-df_3['num7'])==5) & ((df_3['num9']-df_3['num8'])==5) & ((df_3['num10']-df_3['num9'])==5)

df_4['is_diff_5'] = ((df_4['num2']-df_4['num1'])==5) & ((df_4['num3']-df_4['num2'])==5) & ((df_4['num4']-df_4['num3'])==5) & ((df_4['num5']-df_4['num4'])==5) & ((df_4['num6']-df_4['num5'])==5) & ((df_4['num7']-df_4['num6'])==5) & ((df_4['num8']-df_4['num7'])==5) & ((df_4['num9']-df_4['num8'])==5) & ((df_4['num10']-df_4['num9'])==5)


print('\nBot 0: ', df_0['is_diff_5'].all(),'\nBot 1: ', df_1['is_diff_5'].all(), '\nBot 2: ', df_2['is_diff_5'].all(), '\nBot 3: ', df_3['is_diff_5'].all(),'\nBot 4: ', df_4['is_diff_5'].all(),)

Bot 0:  False
Bot 1:  False
Bot 2:  False
Bot 3:  True
Bot 4:  False

**** Bot 3 always outputs a number 5 more than the previous number, i.e., <b><i>num2 = num1 + 5, num3 =  num2 + 5</i></b> ....and so on

In [70]:
df_1['is_diff_5'].value_counts()

False    100000
Name: is_diff_5, dtype: int64

#### Which sources give all zeros as outputs?

In [71]:
(df[num_cols].sum(axis=1)==0).value_counts()

False    499976
True         24
dtype: int64

In [72]:
df.loc[df[num_cols].sum(axis=1)==0]['source'].unique()

array([2, 4])

## <center>Feature Engineering<center>

In [73]:
df.head()

,source,num1,num2,num3,num4,num5,num6,num7,num8,num9,num10
0,0,2,5,2,5,6,2,1,8,1,3
1,1,1747,1749,1751,1758,1765,1767,1772,1774,1783,1785
2,2,65056,195168,1561344,7806720,31226880,187361280,749445120,6745006080,6745006080,6745006080
3,3,2855,2860,2865,2870,2875,2880,2885,2890,2895,2900
4,4,11440,57200,286000,1430000,7150000,35750000,178750000,893750000,4468750000,22343750000

In [74]:
# Are there only single digit numbers in the o/p (not all zeros)
df['all_single_digits'] = ((df[num_cols]==0).sum(axis=1)!=10) & ((df[num_cols]<10).sum(axis=1) == 10)
df['all_single_digits'] = df['all_single_digits'].astype(int)

# Are 10 numbers in a non-decreasing order?
df['is_non_decreasing'] = (df['num2']>=df['num1']) & (df['num3']>=df['num2']) & (df['num4']>=df['num3']) & (df['num5']>=df['num4']) & (df['num6']>=df['num5']) & (df['num7']>=df['num6']) & (df['num8']>=df['num7']) & (df['num9']>=df['num8']) & (df['num10']>=df['num9'])
df['is_non_decreasing'] = df['is_non_decreasing'].astype(int)

# Are the following 9 numbers divisible by the first number?
df['is_div_by_num1'] = (df['num2']%df['num1']) + (df['num3']%df['num1']) + (df['num4']%df['num1']) + (df['num5']%df['num1']) + (df['num6']%df['num1']) + (df['num7']%df['num1']) + (df['num8']%df['num1']) + (df['num9']%df['num1']) + (df['num10']%df['num1']) 
df['is_div_by_num1'] = (df['is_div_by_num1']==0).astype(int)

# Is the next number of o/p divisible by preceeding number?
df['5_times_prev'] = (df['num1']==0) | ((df['num2']/df['num1']==5) & (df['num3']/df['num2']==5) & (df['num4']/df['num3']==5) & (df['num5']/df['num4']==5) & (df['num6']/df['num5']==5) & (df['num7']/df['num6']==5) & (df['num8']/df['num7']==5) & (df['num9']/df['num8']==5) & (df['num10']/df['num9']==5) )
df['5_times_prev'] = df['5_times_prev'].astype(int)

# Is the difference between consecutive numbers less than 10?
df['is_diff_less_than_10'] = ((df['num2']-df['num1'])<10) & ((df['num3']-df['num2'])<10) & ((df['num4']-df['num3'])<10) & ((df['num5']-df['num4'])<10) & ((df['num6']-df['num5'])<10) & ((df['num7']-df['num6'])<10) & ((df['num8']-df['num7'])<10) & ((df['num9']-df['num8'])<10) & ((df['num10']-df['num9'])<10)
df['is_diff_less_than_10'] = df['is_diff_less_than_10'].astype(int)

# Is the next number greater than previous number by exactly 5?
df['is_diff_5'] = ((df['num2']-df['num1'])==5) & ((df['num3']-df['num2'])==5) & ((df['num4']-df['num3'])==5) & ((df['num5']-df['num4'])==5) & ((df['num6']-df['num5'])==5) & ((df['num7']-df['num6'])==5) & ((df['num8']-df['num7'])==5) & ((df['num9']-df['num8'])==5) & ((df['num10']-df['num9'])==5)
df['is_diff_5'] = df['is_diff_5'].astype(int)

# Is the difference between consecutive numbers less than 10 but not all differences are equal to 5?
df['diff_less_than_10_but_not_5'] = df['is_diff_less_than_10'] * (1-df['is_diff_5'])
df['diff_less_than_10_but_not_5'] = df['diff_less_than_10_but_not_5'].astype(int)

df.head(16)

,source,num1,num2,num3,num4,num5,num6,num7,num8,num9,num10,all_single_digits,is_non_decreasing,is_div_by_num1,5_times_prev,is_diff_less_than_10,is_diff_5,diff_less_than_10_but_not_5
0,0,2,5,2,5,6,2,1,8,1,3,1,0,0,0,1,0,1
1,1,1747,1749,1751,1758,1765,1767,1772,1774,1783,1785,0,1,0,0,1,0,1
2,2,65056,195168,1561344,7806720,31226880,187361280,749445120,6745006080,6745006080,6745006080,0,1,1,0,0,0,0
3,3,2855,2860,2865,2870,2875,2880,2885,2890,2895,2900,0,1,0,0,1,1,0
4,4,11440,57200,286000,1430000,7150000,35750000,178750000,893750000,4468750000,22343750000,0,1,1,1,0,0,0
5,0,4,9,5,4,8,6,6,7,7,2,1,0,0,0,1,0,1
6,1,1487,1491,1498,1503,1512,1514,1518,1522,1524,1528,0,1,0,0,1,0,1
7,2,18850,18850,113100,452400,452400,1809600,3619200,3619200,7238400,50668800,0,1,1,0,0,0,0
8,3,8962,8967,8972,8977,8982,8987,8992,8997,9002,9007,0,1,0,0,1,1,0
9,4,2870,14350,71750,358750,1793750,8968750,44843750,224218750,1121093750,5605468750,0,1,1,1,0,0,0
10,0,1,6,5,8,8,8,2,6,9,6,1,0,1,0,1,0,1
11,1,5060,5068,5069,5075,5081,5085,5090,5091,5099,5106,0,1,0,0,1,0,1
12,2,72369,434214,868428,4342140,39079260,351713340,703426680,1406853360,11254826880,56274134400,0,1,1,0,0,0,0
13,3,6270,6275,6280,6285,6290,6295,6300,6305,6310,6315,0,1,0,0,1,1,0
14,4,9270,46350,231750,1158750,5793750,28968750,144843750,724218750,3621093750,18105468750,0,1,1,1,0,0,0
15,0,7,5,3,3,8,9,8,6,7,2,1,0,0,0,1,0,1

## <center>Modelling<center>

### Basic Classification Models

In [75]:
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix

In [76]:
X = df.iloc[:, 11:].values
y = df.iloc[:, 0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [77]:
# Classifiers
clf1 = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=0)
clf2 = LogisticRegression()
clf3 = SVC(kernel='rbf', random_state=0)

In [78]:
# Fitting data to the models
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

# Predicting
y_pred_1 = clf1.predict(X_test)
y_pred_2 = clf2.predict(X_test)
y_pred_3 = clf3.predict(X_test)

### Results

In [82]:
cm1 = confusion_matrix(y_test, y_pred_1)
cm2 = confusion_matrix(y_test, y_pred_2)
cm3 = confusion_matrix(y_test, y_pred_3)

print('\nRandom Forest Model,    Accuracy: ',accuracy_score(y_test, y_pred_1),'\n', cm1)
print('\nLogistic Regression Model,    Accuracy: ',accuracy_score(y_test, y_pred_2),'\n', cm2)
print('\nSupport Vector Classifier Model,    Accuracy: ',accuracy_score(y_test, y_pred_3),'\n', cm3)

Random Forest Model,    Accuracy:  0.99996
 [[10127     0     0     0     0]
 [    0 10088     0     0     0]
 [    0     0  9955     0     2]
 [    0     0     0  9859     0]
 [    0     0     0     0  9969]]

Logistic Regression Model,    Accuracy:  0.99996
 [[10127     0     0     0     0]
 [    0 10088     0     0     0]
 [    0     0  9955     0     2]
 [    0     0     0  9859     0]
 [    0     0     0     0  9969]]

Support Vector Classifier Model,    Accuracy:  0.99996
 [[10127     0     0     0     0]
 [    0 10088     0     0     0]
 [    0     0  9955     0     2]
 [    0     0     0  9859     0]
 [    0     0     0     0  9969]]

### Neural Network Model

In [80]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
y_train_nn = onehotencoder.fit_transform(y_train.reshape(-1,1)).toarray()
y_test_nn = onehotencoder.transform(y_test.reshape(-1,1)).toarray()

import keras
from keras.models import Sequential
from keras.layers import Dense
    
# Building the Neural Network
model = Sequential()
    
model.add(Dense(units=5, kernel_initializer='glorot_uniform', activation='relu', input_dim=7))
model.add(Dense(units=5, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train_nn, batch_size=32, nb_epoch=20)

# Predictions
y_pred_nn = model.predict(X_test)

Epoch 1/20
450000/450000 [==============================] - 23s 51us/step - loss: 0.1068 - accuracy: 0.9723
Epoch 2/20
450000/450000 [==============================] - 23s 52us/step - loss: 3.1937e-04 - accuracy: 1.0000
Epoch 3/20
450000/450000 [==============================] - 23s 51us/step - loss: 1.9387e-04 - accuracy: 1.0000
Epoch 4/20
450000/450000 [==============================] - 23s 51us/step - loss: 1.2810e-04 - accuracy: 1.0000
Epoch 5/20
450000/450000 [==============================] - 24s 52us/step - loss: 8.0632e-05 - accuracy: 1.0000
Epoch 6/20
450000/450000 [==============================] - 24s 53us/step - loss: 6.5160e-05 - accuracy: 1.0000
Epoch 7/20
450000/450000 [==============================] - 26s 58us/step - loss: 6.4763e-05 - accuracy: 1.0000
Epoch 8/20
450000/450000 [==============================] - 24s 54us/step - loss: 5.8938e-05 - accuracy: 1.0000
Epoch 9/20
450000/450000 [==============================] - 23s 51us/step - loss: 5.6834e-05 - accuracy: 1.0000
Epoch 10/20
450000/450000 [==============================] - 27s 59us/step - loss: 6.4426e-05 - accuracy: 1.0000
Epoch 11/20
450000/450000 [==============================] - 23s 52us/step - loss: 6.0262e-05 - accuracy: 1.0000
Epoch 12/20
450000/450000 [==============================] - 23s 52us/step - loss: 6.2277e-05 - accuracy: 1.0000
Epoch 13/20
450000/450000 [==============================] - 25s 55us/step - loss: 5.7152e-05 - accuracy: 1.0000
Epoch 14/20
450000/450000 [==============================] - 23s 51us/step - loss: 5.8319e-05 - accuracy: 1.0000
Epoch 15/20
450000/450000 [==============================] - 23s 52us/step - loss: 5.1924e-05 - accuracy: 1.0000
Epoch 16/20
450000/450000 [==============================] - 23s 51us/step - loss: 5.7644e-05 - accuracy: 1.0000
Epoch 17/20
450000/450000 [==============================] - 23s 51us/step - loss: 5.4161e-05 - accuracy: 1.0000
Epoch 18/20
450000/450000 [==============================] - 23s 51us/step - loss: 5.1970e-05 - accuracy: 1.0000
Epoch 19/20
450000/450000 [==============================] - 23s 52us/step - loss: 6.3092e-05 - accuracy: 1.0000
Epoch 20/20
450000/450000 [==============================] - 24s 54us/step - loss: 5.8161e-05 - accuracy: 1.0000

In [81]:
y_pred_4 = np.argmax(y_pred_nn, axis=1)
cm4 = confusion_matrix(y_test, y_pred_4)
print('\nNeural Network Model,    Accuracy: ',accuracy_score(y_test, y_pred_4),'\n', cm4)

Neural Network Model,    Accuracy:  0.99996
 [[10127     0     0     0     0]
 [    0 10088     0     0     0]
 [    0     0  9955     0     2]
 [    0     0     0  9859     0]
 [    0     0     0     0  9969]]